repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: git@github.com:psf/black.git
    rev: 24.10.0
    hooks:
      - id: black
        name: Black code formatter
        args: [--line-length=120]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.1"
    hooks:
      - id: ruff
        name: ruff (test)
        args:
          - "--fix"
          - "--select=PERF,PL,B,S,F,W,E,I,TID"
          - "--line-length=120"
          - "--verbose"
          - "--ignore=S101,S603,PLR2004,PLW0603,PLW0602"
        files: ^.*(test.*\.py|.*test\.py)$

      - id: ruff
        name: ruff (normal)
        args:
          - "--fix"
          - "--select=PERF,PL,B,S,F,W,E,I,TID"
          - "--line-length=120"
          - "--verbose"
          - "--ignore=PLR2004,PLW0603,PLW0602"
        exclude: ^.*(test.*\.py|.*test\.py)$



  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -n 6
        language: system
        files: ^.*(test_.*\.py|.*_test\.py)$
        pass_filenames: false
        always_run: true
